#!/usr/bin/with-contenv bash

# Current Transcoder location
FILENAME="/usr/lib/plexmediaserver/Plex Transcoder"
# Size to distinguish between patch and Transcoder
MAXSIZE=200000
# Get size of file
FILESIZE=$(stat -c%s "$FILENAME")

if (( FILESIZE < MAXSIZE )); then
  echo "Already nvdec patched!"
else
  mv /usr/lib/plexmediaserver/Plex\ Transcoder /usr/lib/plexmediaserver/Plex\ Transcoder2
  echo "#!/bin/sh" > /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "marap=$(cut -c 10-14 <<<"$@")" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "if [ $marap == "h264" ] || [ $marap == "vc1" ] || [ $marap == "hevc" ] || [ $marap == "mpeg2video" ] || [ $marap == "vp8" ] || [ $marap == "vp9" ] || [ ]; then" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "     exec /usr/lib/plexmediaserver/Plex\ Transcoder2 -hwaccel nvdec "$@"" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "else" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "     exec /usr/lib/plexmediaserver/Plex\ Transcoder2 "$@"" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  echo "fi" >> /usr/lib/plexmediaserver/Plex\ Transcoder
  chmod 755 /usr/lib/plexmediaserver/Plex\ Transcoder
  chmod u+x /usr/lib/plexmediaserver/Plex\ Transcoder
fi
